import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Dumka",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <title>Dumka 🦖</title>
        <meta name="description" content="Dumka - A Modern Experience" />
        <meta
          name="description"
          content="Unite people into teams for collaborative work"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta itemProp="name" content="Dumka - A Modern Experience" />
        <meta
          itemProp="description"
          content="Unite people into teams for collaborative work"
        />
        <meta itemProp="image" content="https://dumka.org/overlay.jpg" />
        <meta property="og:image" content="https://dumka.org/overlay.jpg" />

        <meta property="og:title" content="Dumka - A Modern Experience" />
        <meta
          property="og:description"
          content="Unite people into teams for collaborative work"
        />
        <meta name="twitter:card" content="https://dumka.org/overlay.jpg" />
        <meta name="twitter:site" content="@dumka" />
        <meta name="twitter:title" content="Dumka - A Modern Experience" />
        <meta
          name="twitter:description"
          content="Unite people into teams for collaborative work"
        />
        <meta name="twitter:image" content="https://dumka.org/overlay.jpg" />
        <meta property="line:title" content="Dumka - A Modern Experience" />
        <meta
          property="line:description"
          content="Unite people into teams for collaborative work"
        />
        <meta
          property="pinterest:description"
          content="Dumka - A Modern Experience"
        />
        <meta property="reddit:title" content="Dumka - A Modern Experience" />
        <meta property="telegram:title" content="Dumka - A Modern Experience" />
        <meta property="tumblr:title" content="Dumka - A Modern Experience" />
        <meta property="viber:title" content="Dumka - A Modern Experience" />
        <meta property="weibo:title" content="Dumka - A Modern Experience" />
        <meta property="whatsapp:title" content="Dumka - A Modern Experience" />
        <meta property="linkedin:title" content="Dumka - A Modern Experience" />
        <meta property="vk:title" content="Dumka - A Modern Experience" />
        <meta property="mailru:title" content="Dumka - A Modern Experience" />
        <meta
          property="livejournal:title"
          content="Dumka - A Modern Experience"
        />
        <meta
          property="workplace:title"
          content="Dumka - A Modern Experience"
        />
        <meta property="pocket:title" content="Dumka - A Modern Experience" />
        <meta
          property="instapaper:title"
          content="Dumka - A Modern Experience"
        />
        <meta property="hatena:title" content="Dumka - A Modern Experience" />
        <meta
          property="facebookMessenger:title"
          content="Dumka - A Modern Experience"
        />
        <meta property="email:subject" content="Dumka - A Modern Experience" />
        <meta property="gab:title" content="Dumka - A Modern Experience" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
